openapi: 3.0.1
info:
  title: ActionGPT Gmail Server
  version: "1.0"
  description: >
    Minimal OpenAPI 3.0 schema for ChatGPT Actions validation.
    Provides a single /health endpoint for connection testing.

servers:
  - url: https://actiongpt-server.ngrok.app

paths:
  /health:
    get:
      summary: Health Check
      operationId: health_check
      responses:
        "200":
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
