openapi: 3.1.0
info:
  title: ActionGPT Test API
  version: "1.0"
  description: Minimal test schema for ChatGPT Actions import validation.
servers:
  - url: "https://actiongpt-server.ngrok.app"
paths:
  /health:
    get:
      summary: Health Check
      operationId: health_check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
# redeploy Mon Oct  6 18:17:11 UTC 2025
